# DeltaInventory Configuration File

# DeltaEssentials Database name
Database: Main

# Forced Gamemode settings
# Set to SURVIVAL, CREATIVE, ADVENTURE, or SPECTATOR to enable a forced gamemode.
# Set to NONE to disable a forced gamemode.
# Add "DeltaInv.ForcedGameMode.Bypass" to ignore forced gamemode.
ForcedGameMode: NONE

# Should all effects be cleared when logging into the server?
ClearEffectsOnLogin: False

# Debug Mode (for developers)
DebugMode: False
