# DeltaInventory Configuration File

# DeltaEssentials Database name
Database: Main

# Players are not allowed to switch to these gamemodes unless they have the bypass permission.
# Options: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
# Permission example: DeltaInv.Disabled.Bypass.SPECTATOR
DisabledGameModes:
- ADVENTURE
- SPECTATOR

# Gamemode that players will be forced into when joining this server.
# Options: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR, NONE
# Permission example: DeltaInv.Forced.Bypass
ForcedGameMode: NONE

# Should all effects be cleared when logging into the server?
ClearEffectsOnLogin: False

# Debug Mode (for developers)
DebugMode: False
