# DeltaInventory Configuration File

# File path to the player data folder
# If the path is ' ', the plugin's data folder (.../plugins/DeltaInventory/PlayerData/) will be used
PlayerDataFolder: ' '

# Players are not allowed to switch to these gamemodes unless they have the bypass permission.
# Options: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
# Permission example: DeltaInv.Disabled.Bypass.SPECTATOR
DisabledGameModes:
- ADVENTURE
- SPECTATOR

# Gamemode that players will be forced into when joining this server.
# Options: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR, NONE
# Permission example: DeltaInv.Forced.Bypass
ForcedGameMode: NONE

# Should all effects be cleared when logging into the server?
ClearEffectsOnLogin: False

# Debug Mode (for developers)
DebugMode: True
