# DeltaInventory Configuration File

# DeltaEssentials Database name
Database: Main

# Should all effects be cleared when logging into the server?
ClearEffectsOnLogin: False

# Forced Gamemode settings
ForcedGameMode:
  # Set to true to enable a forced gamemode.
  # Add "DeltaInv.ForcedGameMode.Bypass" permission to bypass.
  Enable: False
  # Options include SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  GameMode: SURVIVAL

# Debug Mode (for developers)
DebugMode: False
