name: DeltaInventory
main: com.yahoo.tracebachi.DeltaInventory.DeltaInventoryPlugin
version: 1.2
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
depend: [xAuth, DeltaRedis, DeltaEssentials]
# Add all minigames on your server to this list to help
# avoid the wrong inventories being saved on shutdown
loadbefore: [MobArena, FloorIsLava]

permissions:
  DeltaInv.SingleInv:
    description: Maintains a single inventory for all gamemodes.
  DeltaInv.ForcedGameMode.Bypass:
    description: Allows player to bypass forced gamemode restriction.
