name: DeltaInventory
main: com.yahoo.tracebachi.DeltaInventory.DeltaInventoryPlugin
version: 1.0
author: Trace Bachi (tracebachi@yahoo.com, BigBossZee)
depend: [xAuth, DeltaEssentials]

permissions:
  DeltaInv.SingleInv:
    description: Maintains a single inventory for all gamemodes.
  DeltaInv.ForcedGameMode.Bypass:
    description: Allows player to bypass forced gamemode restriction.
